let reponse_question = [
    {
        question:"Simplon est-elle la première et seule formation en son genre ?",
        reponse:"Bien qu’elle se distingue par son format à la fois intensif, vraiment gratuit (voir « gratuité »), tourné vers les publics éloignés de l’emploi et sous-représentés dans le numérique, Simplon n’est pas la première formation de ce type, ni la seule.Tout d’abord, plusieurs autres formations existaient déjà en France avant l’apparition de Simplon.co en 2013, comme la Web@cadémie, R2K, 3WAcadémie ou encore Cefim et bien d’autres dans les territoires…Par la suite, d'autres se sont créées simultanément à Simplon, comme Le Wagon, l’Ecole 42, Webforce3...Puis, des formations  se sont créées au contact de Simplon (copycats, forks ou franchisés s’étant autonomisés) : Wild Code School (auparavant Simplon Village dans le Perche), Pop School, Access Code School ou Pôle S,...Enfin, des formations se sont mises en place dans le sillage du dispositif Grande École du Numérique et complètent cette liste. Toutes sont intéressantes, certaines sont innovantes, et si Simplon.co présente la particularité de proposer la gratuité et l’approche par compétence en pédagogie active prioritairement aux publics les plus éloignés, nous formons ensemble une véritable filière, riche et complémentaire.En effet, nous fournissons des solutions différentes, parfois articulées en fonction de leur durée (entre 3 mois et 3 ans), des métiers visés (développeur, data analyste, technicien IA, etc.), des technologies (C, PHP, Ruby, Java,…), de leur pédagogie (descendante ou active, avec ou sans formateurs physiques, présentielle et distancielle)...Toutes ne visent pas les mêmes publics et la plupart sont concentrées dans les grandes agglomérations alors que d’autres visent les territoires fragiles.Parmi elles, Simplon.co propose une identité unique en son genre, en s’ouvrant véritablement à tous (sans distinction d’âge, de niveau scolaire et d’origine territoriale) et en proposant des formations intégralement gratuites.De la même façon, Simplon intègre depuis son origine une préoccupation centrale autour de la représentation des effectifs féminins dans ces métiers du numérique. Sa place dans des territoires complexes en lien avec la géographie prioritaire, la ruralité, les Outre-mer ou l’international est rarement discutée, notamment du fait de son implantation dans les zones les plus fragilisées et de sa croissance. Enfin, certains de ses piliers pédagogiques comme le « learning by teaching » sont également très caractéristiques et originaux."
    },
    {
        question:"Quelle différence entre Simplon.co et 42 ?",
        reponse:"Il s’agit de la question la plus fréquente qu’on nous pose, et notre réponse reste inchangée depuis le lancement conjoint de Simplon et de l'École 42 qui ont été quasi simultanés en 2013. Si les deux concepts comportent effectivement beaucoup de ressemblances, elles ont aussi leurs particularités.Elles sont similaires, car nous appartenons à la même “vague”, à la même démarche visant à innover pour résoudre l’absurdité patente entre un besoin de compétences non satisfait et des talents potentiels au chômage en manque de formation.Similaires, car elles sont gratuites et que désormais l'École 42 n’a plus de limite d’âge ; similaires, enfin, parce que l’on y trouve une volonté d’innovation pédagogique.Mais les deux structures ont aussi leurs différences, notamment sur les formations qu’elles proposent : si l'École 42 choisit de viser un public plus exclusif, les séniors multi-poly-compétents, Simplon forme également des apprenants plus jeunes. La durée de formation diffère aussi, s’étendant sur 2 à 3 ans pour l’Ecole 42 contre 7 mois en moyenne chez Simplon. Les deux entreprises ne procèdent pas à leurs sélections selon les mêmes critères : ceux-ci peuvent être par exemple moins élitistes et plus inclusifs chez Simplon.co, visant particulièrement les femmes, les personnes en difficulté ou encore les territoires déclassés.Enfin, la question du présentiel les différencie une nouvelle fois, dans la mesure où les professeurs de Simplon sont présents en permanence et animent leurs formations au sein des Fabriques en présentiel, ou en téléprésentiel.Sur le modèle économique, grosse différence aussi : les dirigeants de Simplon ne sont pas milliardaires et donc ne peuvent s’affranchir d’un modèle économique. Nos différences n’empêchent pas une véritable entente et collaboration entre les deux projets : les apprenants basculent entre elles selon leurs parcours, certains étudiants de l’Ecole 42 étant même devenus professeurs à Simplon !  Des liens particuliers se sont entretenus ; participation commune aux Hackathons, identité commune de “Grande École du Numérique”.. Certains opérateurs, comme OCP au Maroc, n’ont pas choisi et ont déployé nos deux modèles. “Born to code” (Ecole 42)  et “In Code We Trust” ou “Shift to digital inclusion” (Simplon), malgré leurs différences, continuent de se construire ensemble. "
    }
    ,
    {
        question:"Quelle sélection et quels critères pour entrer à Simplon.co ?",
        reponse:"Les critères sociaux sont prépondérants et préalables pour accéder à nos formations qui sont réellement et intégralement gratuites, d’où le fait que nous souhaitons privilégier un public en particulier. Les demandeurs d’emploi (décrocheurs, ou longue durée), les personnes en reconversion et les seniors, les publics réfugiés ou primo-arrivants, les personnes en situation de handicap, les allocataires de minimas sociaux et les publics éloignés du numérique ou de l’emploi sont notamment concernés. Mais ce n’est pas suffisant, car le nombre de places par session est limité.Dans une autre mesure, 7 mois sans pouvoir forcément bénéficier de revenus; tout en assistant à une formation intensive à plein temps dont la pédagogie est active et non scolaire ne convient pas systématiquement à tout le monde. C’est donc au travers d’une sélection sur la base de la motivation, de l’appétence, de la capacité à travailler en équipe, de la prédisposition au métier numérique visé par la formation et de la compatibilité avec le modèle pédagogique (autonomie, pédagogies actives, mode projet, peer-learning,…) ainsi qu’à l’organisation de Simplon.co (pair programming, travail collaboratif) que se décide l’admission.Localement, en fonction des partenaires, des territoires et des financements, d’autres critères peuvent intervenir : l’âge (moins de 25 ans ou au contraire séniors), la géographie (quartiers politique de la ville ou ruralité, résidence dans l’agglomération de la fabrique, etc.), le niveau d’études (pas de diplôme et décrocheur pour la Grande École du Numérique, BAC + 2 pour certaines formations, etc).La formation Simplon est donc à la fois inclusive et sélective, de 10 à 50% des candidatures selon les territoires et les sessions. Cette sélection parfois élevée n’est pas due aux critères habituels de niveau de diplôme, d’expérience, de tests techniques ou de pré-requis. De même, certaines populations telles que les femmes, les personnes issues des quartiers populaires ou encore les non-bacheliers sont clairement favorisées dans notre recrutement."
    }
]

let ecran=document.getElementById('ecran');
function findAnswser(string){
    reponse_question.forEach(element=>{
        if(element.question==string){
            ecran.innerHTML=element.reponse;
            titre.innerHTML=element.question;
            responsive_tab.classList.remove('responsive-tab-show');
        }
    })
}


// affichage responsive
let responsive_tab=document.querySelector('.responsive-tab');
let tab=document.getElementById('tab');
let titre=document.getElementById('titre');
tab.addEventListener('click',()=>{
    responsive_tab.classList.add('responsive-tab-show');
})